name: Build iOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 🔍 Debug - List schemes
        run: xcodebuild -list

      - name: Resolve dependencies
        run: xcodebuild -resolvePackageDependencies

      - name: Build app
        run: |
          xcodebuild -scheme "TennisMatch" -sdk iphoneos -configuration Release \
            archive -archivePath $PWD/build/TennisMatch.xcarchive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/TennisMatch.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/build
